### ISSUE TITLE
intercambios

### ISSUE THREAD

**Issue by fauno** [piratas-ar/dineros#5]
faltaría una forma de cambiar una cantidad de X por otra cantidad de Y, ahora estamos haciendo un egreso y un ingreso

**Comment by sudoaza** [comment]
+1

**Comment by m4tu5** [comment]
+1, lo imagino como una transferencia con un un solo usuario para emitir y recibir (en lugar de 2 que tenemos ahora) y 2 monedas (en lugar de 1 sola)
